spring:
    application:
        name: chamomile-admin
    main:
        allow-bean-definition-overriding: true
    sql:
        init:
            mode: always
    jpa:
        defer-datasource-initialization: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    redis:
        cluster:
            nodes:
                - 10.131.4.85:8093
                - 10.131.4.85:8082
                - 10.131.4.85:8081
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
                max-wait: -1ms
    hazelcast:
        config: hazelcast-dev.yml

server:
    error:
        whitelabel:
            enabled: true
        include-exception: true
        include-message: always
        include-stacktrace: always
    port: 8080

chmm:
    admin:
        zip-password: ENC(42w+KY+TBQZ8tBdadiMu60AJawGby6Mp)
    ##SECURITY
    security:
        loginProcessingUrl: /login
        logoutProcessingUrl: /logout
        usernameParameter: username
        passwordParameter: password
        defaultPasswordEncoder: sha256
        passwordEncoderList: sha256,bcrypt
        rsaPassword:
            use: true
            privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDuf1P3Lat+UvNu50yOb4+yUFJBMYYI9rJITlrKCFuvqVFnhAMD5ZN/ZIPGMFaH3UnsLY2RNDoVIcfF0V6a8cEgpm0AI04GCxBo7tDRKHmeuXfhdJWurneEwgcLs6Y/3xaqOp3PpzoFAWJzJ58Zl9863Ibh4GNa27SgB3T/Bb3TZfSxWfOf+DfRXqvUi+8Tei/w2rj1bYXuDWCiHUgw+1rLaVK9zXbn2++JXU406yrLOasNj6r2SQRbptdyRkfndKiKGGB/5tQDfqpqBXsRtAqis3A0djIgIdlFHGIV6btj++VhYg5qYk1J2U8dF2Xh6kA8wcNW9HEam141aRVuvfJtAgMBAAECggEBAOj6EPfg8SnRtmOcJzjs2h6CQBfXXOvcsYPYpu+9AnOynwbT+m4QEencMq2kAqNuFAxW43f44NRLz276e8Q4bUSLzubXlhxpKnqW7/2h4EyhOO5QiPe/DpntQBy6PakfMHDSGd8DqLXDCH0dM1o49aP2UPzNycCz5tp87llBLpIVoA3Cfk1cqf/7AGr3hQ+FeXLZA9mZd1tvAH2bdIEeVAUjbk4DALyIWROy/6jE8SyHzP4QNm6m5Q27yFuUIbuVg3MTI65uF9nuNDQdeupzyvbYFg9mdV5d1+MxXnIqK5MhPLxFjkyk1cmhEmYYSCFkRukcqaSin6c10HIB5AzFa4ECgYEA+dG9BiJJng4g1an1q3V3Uyiev+fLZokY8sBgv3oJIqdY763u6/bHFPvShFwne6tRbVLyoY/Pp8CNeEwmmuMF8oVfcuOX+ZRsHuoeDicf4/mmOwlYX3E6EHS/ayu9S3Ths8EshK0NJL4IufBKuGxvWrIswU8q0Le8kizB3nNQOJUCgYEA9GXhf35wHFfhDEkbDfU0rtfeFmCskER5u1vwQOD4Pq9ZxjWQdcxWK75Lazii0pRlF46zy64cQYowZWfQMQJbK0JrtZLlV1KgBzYxOvK9x8R4h9EQBCcH8P09druPyo51D97N7ZqD1ovBXxE2orQdZ5dU79rbSKmL3ULZgsWVZHkCgYAY+bcEHfluK8tskQlWku/TCISWev4CykIMQt9pRTIUnNZvX9w7CvjsSCDLysrHumDxpRFMxavlAYMjO7nAUmIN1Pet7MMM2KHWlWFb2N1/VT4hONX09MTxUDqy5DSQjqbh6bYhrYta2QTWUgemWHDpiFahHOES7MuVcZQQQUcL4QKBgCfNI8EwpS9ofGUUzswiH9dNnoSEb/X6wNxrZ6AZQzRqODOYa5NTmMD896lZiuLCeggxHETScRWXXLRXCMfCe3h7E7F5X9ItyZQDFldkStXqwDpWKMaUWK29gDIC77LsKlJQVbcZT9kz32UNF5m9vYAuXA3H1ahqvDVneqbaaK75AoGAaj86dZ9rT493pS1eXpJAhfbp4i51jLzm/ui1c324UvdX3ws1eL50D2T1m7AAz/zCy6QAcLR1b1MQGxqqrNYD12UKY9+xVKMtd4x0mueofK3v3AdBZeRRqGgE7yxrpFFicC0ixeQp09ppMpew1CGH3of/ifbon4Kn2cWdBEjxCdo=
        ignorePatterns:
            - /security/reload
            - /security/jwt/refresh-token
            - /security/jwt/secret-key
            - /security/jwt/authenticate
            - /swagger-ui/**
            - /api-docs/**
            - /swagger-resources/**
            - /v3/api-docs/**
            - /chmm/board/image/download/**
            - /appstore/**
            - /chmm/user/check-verify-code
            - /chmm/user/send-verify-code
            - /chmm/user/change-password
            - /chmm/user/email-check
            - /chmm/user/user-check-id
            - /chmm/user/register
            - /chmm/user/user-check-mobile
            - /security/pre-login
        2fa:
            prelogin:
                check: false
        # custom
        autoconfig:
            use: true
            rememberMe: true
            rememberMeValiditySeconds: 604800
            maximumSessions: -1
            returnUrl: /index.html
    jwt:
        secret: 0PtD9jRs2Q7Cgw38E8CNSBfxSf/ib/mAElN05fhAUU0FXsB3S8F3rfaaCSHy+NWQZkhDbs1SJm+cjdKQX4eHGA==
        access-expired-time: 1800000 #30분
        refresh-expired-time: 86400000 #24시간
    ## JWT CORS
    cors:
        configurations:
            - pattern: "/**"
              allowed-origins:
                  - "http://10.131.156.253:3000"
                  - "http://localhost:8080"
                  - "http://localhost:23636"
              allowed-methods:
                  - "GET"
                  - "POST"
              allowed-headers:
                  - "Authorization"
                  - "Content-Type"
              allow-credentials: false
              max-age: 3600
    2fa:
        prelogin:
            check: false


    #Hikari DataSource
    jdbc:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbcUrl: jdbc:log4jdbc:mysql://10.131.7.143:3306/chamomile3?autoReconnect=true&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: ENC(42w+KY+TBQZ8tBdadiMu60AJawGby6Mp)
        maximumPoolSize: 10
        connectionTimeout: 30000
        maxLifetime: 1800000

    ##MAPPER
    mapper:
        interval: 60000
        refreshable: true
        config-location: classpath:/sql/config/sqlMapConfig.xml
        refreshable-mapper-locations:
            - classpath:/sql/service/*.xml
#            - classpath*:/sql/service/mobile/*.xml
        mapper-locations: sql/service/*.xml
    txPointcut:
        expression: (execution(* net.lotte.chamomile.admin..*ServiceImpl.*(..)))

    #FILE
    file:
        repositoryPath: /opt/files/common
        allowExtension: ""
        maxSize: 20MB
        directoryDateNameFormat: yyyy/MM

    #MAIL
    mail:
        from: chamomile@lotte.net

    #MOBILE
#    mobile:
#        admin:
#            controller: true
#            file: /opt/files/mobile

springdoc:
    swagger-ui:
        version: v1.0.0
        path: /swagger-ui.html
        groups-order: DESC
        operationsSorter: method
        disable-swagger-default-url: true
        display-request-duration: true
    api-docs:
        path: /api-docs
        groups:
            enabled: true
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    packages-to-scan: net.lotte.chamomile.admin

