DROP TABLE IF EXISTS chmm_board_info;
CREATE TABLE chmm_board_info
(
    board_id bigint generated by default as identity,
    board_type char(1) NOT NULL,
    title varchar(50) NOT NULL,
    mail_yn char(1) DEFAULT NULL,
    contents varchar(200) DEFAULT NULL,
    notice_yn char(1) DEFAULT NULL,
    public_yn char(1) DEFAULT NULL,
    apply_start_dtm varchar(8) DEFAULT NULL,
    apply_end_dtm varchar(8) DEFAULT NULL,
    view_cnt bigint DEFAULT 0,
    sys_insert_dtm timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
    sys_insert_user_id varchar(255) DEFAULT NULL,
    sys_update_user_id varchar(255) DEFAULT NULL,
    sys_update_dtm timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
    PRIMARY KEY (board_id)
);

DROP TABLE IF EXISTS chmm_board_user_map;
CREATE TABLE chmm_board_user_map
(
    board_id bigint NOT NULL,
    user_id varchar(255) NOT NULL,
    PRIMARY KEY (board_id, user_id)
);

DROP TABLE IF EXISTS chmm_board_image_map;
CREATE TABLE chmm_board_image_map
(
	board_id BIGINT NOT NULL,
	image_url VARCHAR(255) NOT NULL,
	PRIMARY KEY(board_id, image_url)
);
